### ISSUE TITLE
how can i set a custom format and have it appear as the topmost search result when typing "ts"

### ISSUE THREAD

**Issue by fourteen-1** [DustofShadows/Smart-Timestamps-FlowLauncher-Plugin#1]
how can i set a custom format and have it appear as the topmost search result when typing "ts"

**Comment by DustofShadows** [comment]
You need to find your plugin file. If I remember correctly, you can search in the FlowLauncher for `FlowLauncher UserData Folder` -> `Plugins ` -> ~ `Smart Timestamps`

To use a custom format, you can alter the code within the "index.ts" file, starting at line 92:
```return [
    {
        title: date.format("DD/MM/YY"),
        subtitle: "<DD/MM/YY>",
        method: "copy_result",
        params: [date.format("DD/MM/YY")],
    },
    {
        title: date.format("dddd, DD.MM"),
        subtitle: "<dddd, DD.MM>",
        method: "copy_result",
        params: [date.format("dddd, DD.MM")],
    },
```

You can also make more complex function calls like I implemented with the `function formatTimeFromNow` (line 47). In this case you can return it like this:
```
 {
        title: `in ${formatTimeFromNow(date)}`,
        subtitle: `Accurately, in <time>`,
        method: "copy_result",
        params: [`in ${formatTimeFromNow(date)}`],
    },
```

When you alter the code, make sure that the file is saved, otherwise the changes will not apply.

**Comment by DustofShadows** [comment]
You need to find the plugin file. If I remember correctly, you can search in the FlowLauncher for `FlowLauncher UserData Folder` -> `Plugins ` -> ~ `Smart Timestamps`

To use a custom format, you can alter the code within the "index.ts" file, starting at line 92:
```return [
    {
        title: date.format("DD/MM/YY"),
        subtitle: "<DD/MM/YY>",
        method: "copy_result",
        params: [date.format("DD/MM/YY")],
    },
    {
        title: date.format("dddd, DD.MM"),
        subtitle: "<dddd, DD.MM>",
        method: "copy_result",
        params: [date.format("dddd, DD.MM")],
    },
```

You can also make more complex function calls like I implemented with the `function formatTimeFromNow` (line 47). In this case you can return it like this:
```
 {
        title: `in ${formatTimeFromNow(date)}`,
        subtitle: `Accurately, in <time>`,
        method: "copy_result",
        params: [`in ${formatTimeFromNow(date)}`],
    },
```

When you alter the code, make sure that the file is saved - you may eventually need to reload the Plugin-Data.

**Comment by fourteen-1** [comment]
I tried this but it didnt work. then i tried it with index.js and it worked. still would be really great if there was a more straight forward way to set a custom format for people who are not well-versed in code. also the custom timestamp is not showing up as the top-most query even after putting the code before all other timestamp formats.
